logging:
  file: logs/simple_ws.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [user=%X{user} ip=%X{ip} %X{method}] - %msg%n"
  level:
    org.springframework.web: INFO
    com.antonchar.userservice.controller: DEBUG

liquibase:
  enabled: true
  change-log: classpath:liquibase/userservice.changelog.xml

db:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/user_service
  username: root
  password: root

#server:
#   port: 8888